import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import { createClient } from "@/lib/supabase/server";

/**
 * Journal invites — link-based. The owner POSTs to generate a token, copies
 * the resulting `/invite/<token>` URL, and shares it via any channel (Slack,
 * WhatsApp, email). No email integration required for MVP.
 *
 * The recipient visits `/invite/<token>`, clicks Accept, and is added as a
 * member via the `accept_journal_invite` SQL RPC (which bypasses RLS safely
 * under SECURITY DEFINER).
 */

type RouteContext = { params: Promise<{ id: string }> };

const createInviteSchema = z.object({
  role: z.enum(["member", "viewer"]).default("member"),
  expires_in_days: z.number().int().min(1).max(30).default(7).optional(),
});

export async function GET(
  _request: NextRequest,
  context: RouteContext,
): Promise<NextResponse> {
  try {
    const { id } = await context.params;
    const supabase = await createClient();
    const {
      data: { user },
      error: authError,
    } = await supabase.auth.getUser();

    if (authError || !user) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const { data: myMembership } = await supabase
      .from("journal_members")
      .select("role")
      .eq("journal_id", id)
      .eq("user_id", user.id)
      .maybeSingle();

    if (!myMembership || myMembership.role !== "owner") {
      return NextResponse.json(
        { error: "Only journal owners can view invites." },
        { status: 403 },
      );
    }

    // Return only non-revoked + non-accepted + non-expired invites (active
    // ones). Also return token so UI can construct the share URL.
    const { data, error } = await supabase
      .from("journal_invites")
      .select("*")
      .eq("journal_id", id)
      .is("revoked_at", null)
      .is("accepted_at", null)
      .gt("expires_at", new Date().toISOString())
      .order("created_at", { ascending: false });

    if (error) {
      console.error("[invites GET]", error.message);
      return NextResponse.json({ error: error.message }, { status: 500 });
    }

    return NextResponse.json({ data: data ?? [] });
  } catch (err: unknown) {
    const message = err instanceof Error ? err.message : "Internal server error";
    return NextResponse.json({ error: message }, { status: 500 });
  }
}

export async function POST(
  request: NextRequest,
  context: RouteContext,
): Promise<NextResponse> {
  try {
    const { id } = await context.params;
    const supabase = await createClient();
    const {
      data: { user },
      error: authError,
    } = await supabase.auth.getUser();

    if (authError || !user) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const { data: myMembership } = await supabase
      .from("journal_members")
      .select("role")
      .eq("journal_id", id)
      .eq("user_id", user.id)
      .maybeSingle();

    if (!myMembership || myMembership.role !== "owner") {
      return NextResponse.json(
        { error: "Only journal owners can generate invites." },
        { status: 403 },
      );
    }

    const body: unknown = await request.json().catch(() => ({}));
    const parsed = createInviteSchema.safeParse(body);
    if (!parsed.success) {
      return NextResponse.json(
        { error: "Validation failed", details: parsed.error.flatten().fieldErrors },
        { status: 400 },
      );
    }

    const expiresInDays = parsed.data.expires_in_days ?? 7;
    const expiresAt = new Date(Date.now() + expiresInDays * 24 * 60 * 60 * 1000);

    // Token default is generated by the DB column (generate_invite_token());
    // we don't set it client-side so it can't be influenced.
    const { data, error } = await supabase
      .from("journal_invites")
      .insert({
        journal_id: id,
        role: parsed.data.role,
        created_by_user_id: user.id,
        expires_at: expiresAt.toISOString(),
      })
      .select()
      .single();

    if (error) {
      console.error("[invites POST]", error.message);
      return NextResponse.json({ error: error.message }, { status: 400 });
    }

    return NextResponse.json({ data }, { status: 201 });
  } catch (err: unknown) {
    const message = err instanceof Error ? err.message : "Internal server error";
    return NextResponse.json({ error: message }, { status: 500 });
  }
}
